# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/max/code/z80emu

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/max/code/z80emu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/max/code/z80emu/CMakeFiles /home/max/code/z80emu//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/max/code/z80emu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Z80Emu.out

# Build rule for target.
Z80Emu.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Z80Emu.out
.PHONY : Z80Emu.out

# fast build rule for target.
Z80Emu.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/build
.PHONY : Z80Emu.out/fast

src/Z80/iManager/iManager.o: src/Z80/iManager/iManager.cpp.o

.PHONY : src/Z80/iManager/iManager.o

# target to build an object file
src/Z80/iManager/iManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iManager.cpp.o
.PHONY : src/Z80/iManager/iManager.cpp.o

src/Z80/iManager/iManager.i: src/Z80/iManager/iManager.cpp.i

.PHONY : src/Z80/iManager/iManager.i

# target to preprocess a source file
src/Z80/iManager/iManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iManager.cpp.i
.PHONY : src/Z80/iManager/iManager.cpp.i

src/Z80/iManager/iManager.s: src/Z80/iManager/iManager.cpp.s

.PHONY : src/Z80/iManager/iManager.s

# target to generate assembly for a file
src/Z80/iManager/iManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iManager.cpp.s
.PHONY : src/Z80/iManager/iManager.cpp.s

src/Z80/iManager/iSet/BIT/bitIS.o: src/Z80/iManager/iSet/BIT/bitIS.cpp.o

.PHONY : src/Z80/iManager/iSet/BIT/bitIS.o

# target to build an object file
src/Z80/iManager/iSet/BIT/bitIS.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/BIT/bitIS.cpp.o
.PHONY : src/Z80/iManager/iSet/BIT/bitIS.cpp.o

src/Z80/iManager/iSet/BIT/bitIS.i: src/Z80/iManager/iSet/BIT/bitIS.cpp.i

.PHONY : src/Z80/iManager/iSet/BIT/bitIS.i

# target to preprocess a source file
src/Z80/iManager/iSet/BIT/bitIS.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/BIT/bitIS.cpp.i
.PHONY : src/Z80/iManager/iSet/BIT/bitIS.cpp.i

src/Z80/iManager/iSet/BIT/bitIS.s: src/Z80/iManager/iSet/BIT/bitIS.cpp.s

.PHONY : src/Z80/iManager/iSet/BIT/bitIS.s

# target to generate assembly for a file
src/Z80/iManager/iSet/BIT/bitIS.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/BIT/bitIS.cpp.s
.PHONY : src/Z80/iManager/iSet/BIT/bitIS.cpp.s

src/Z80/iManager/iSet/IXCB/ixcb.o: src/Z80/iManager/iSet/IXCB/ixcb.cpp.o

.PHONY : src/Z80/iManager/iSet/IXCB/ixcb.o

# target to build an object file
src/Z80/iManager/iSet/IXCB/ixcb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/IXCB/ixcb.cpp.o
.PHONY : src/Z80/iManager/iSet/IXCB/ixcb.cpp.o

src/Z80/iManager/iSet/IXCB/ixcb.i: src/Z80/iManager/iSet/IXCB/ixcb.cpp.i

.PHONY : src/Z80/iManager/iSet/IXCB/ixcb.i

# target to preprocess a source file
src/Z80/iManager/iSet/IXCB/ixcb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/IXCB/ixcb.cpp.i
.PHONY : src/Z80/iManager/iSet/IXCB/ixcb.cpp.i

src/Z80/iManager/iSet/IXCB/ixcb.s: src/Z80/iManager/iSet/IXCB/ixcb.cpp.s

.PHONY : src/Z80/iManager/iSet/IXCB/ixcb.s

# target to generate assembly for a file
src/Z80/iManager/iSet/IXCB/ixcb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/IXCB/ixcb.cpp.s
.PHONY : src/Z80/iManager/iSet/IXCB/ixcb.cpp.s

src/Z80/iManager/iSet/IYCB/iycb.o: src/Z80/iManager/iSet/IYCB/iycb.cpp.o

.PHONY : src/Z80/iManager/iSet/IYCB/iycb.o

# target to build an object file
src/Z80/iManager/iSet/IYCB/iycb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/IYCB/iycb.cpp.o
.PHONY : src/Z80/iManager/iSet/IYCB/iycb.cpp.o

src/Z80/iManager/iSet/IYCB/iycb.i: src/Z80/iManager/iSet/IYCB/iycb.cpp.i

.PHONY : src/Z80/iManager/iSet/IYCB/iycb.i

# target to preprocess a source file
src/Z80/iManager/iSet/IYCB/iycb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/IYCB/iycb.cpp.i
.PHONY : src/Z80/iManager/iSet/IYCB/iycb.cpp.i

src/Z80/iManager/iSet/IYCB/iycb.s: src/Z80/iManager/iSet/IYCB/iycb.cpp.s

.PHONY : src/Z80/iManager/iSet/IYCB/iycb.s

# target to generate assembly for a file
src/Z80/iManager/iSet/IYCB/iycb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/IYCB/iycb.cpp.s
.PHONY : src/Z80/iManager/iSet/IYCB/iycb.cpp.s

src/Z80/iManager/iSet/MAINIS/mainIs.o: src/Z80/iManager/iSet/MAINIS/mainIs.cpp.o

.PHONY : src/Z80/iManager/iSet/MAINIS/mainIs.o

# target to build an object file
src/Z80/iManager/iSet/MAINIS/mainIs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/MAINIS/mainIs.cpp.o
.PHONY : src/Z80/iManager/iSet/MAINIS/mainIs.cpp.o

src/Z80/iManager/iSet/MAINIS/mainIs.i: src/Z80/iManager/iSet/MAINIS/mainIs.cpp.i

.PHONY : src/Z80/iManager/iSet/MAINIS/mainIs.i

# target to preprocess a source file
src/Z80/iManager/iSet/MAINIS/mainIs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/MAINIS/mainIs.cpp.i
.PHONY : src/Z80/iManager/iSet/MAINIS/mainIs.cpp.i

src/Z80/iManager/iSet/MAINIS/mainIs.s: src/Z80/iManager/iSet/MAINIS/mainIs.cpp.s

.PHONY : src/Z80/iManager/iSet/MAINIS/mainIs.s

# target to generate assembly for a file
src/Z80/iManager/iSet/MAINIS/mainIs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/MAINIS/mainIs.cpp.s
.PHONY : src/Z80/iManager/iSet/MAINIS/mainIs.cpp.s

src/Z80/iManager/iSet/arithmetic/arithmetic.o: src/Z80/iManager/iSet/arithmetic/arithmetic.cpp.o

.PHONY : src/Z80/iManager/iSet/arithmetic/arithmetic.o

# target to build an object file
src/Z80/iManager/iSet/arithmetic/arithmetic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/arithmetic/arithmetic.cpp.o
.PHONY : src/Z80/iManager/iSet/arithmetic/arithmetic.cpp.o

src/Z80/iManager/iSet/arithmetic/arithmetic.i: src/Z80/iManager/iSet/arithmetic/arithmetic.cpp.i

.PHONY : src/Z80/iManager/iSet/arithmetic/arithmetic.i

# target to preprocess a source file
src/Z80/iManager/iSet/arithmetic/arithmetic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/arithmetic/arithmetic.cpp.i
.PHONY : src/Z80/iManager/iSet/arithmetic/arithmetic.cpp.i

src/Z80/iManager/iSet/arithmetic/arithmetic.s: src/Z80/iManager/iSet/arithmetic/arithmetic.cpp.s

.PHONY : src/Z80/iManager/iSet/arithmetic/arithmetic.s

# target to generate assembly for a file
src/Z80/iManager/iSet/arithmetic/arithmetic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/arithmetic/arithmetic.cpp.s
.PHONY : src/Z80/iManager/iSet/arithmetic/arithmetic.cpp.s

src/Z80/iManager/iSet/bit/bit.o: src/Z80/iManager/iSet/bit/bit.cpp.o

.PHONY : src/Z80/iManager/iSet/bit/bit.o

# target to build an object file
src/Z80/iManager/iSet/bit/bit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/bit/bit.cpp.o
.PHONY : src/Z80/iManager/iSet/bit/bit.cpp.o

src/Z80/iManager/iSet/bit/bit.i: src/Z80/iManager/iSet/bit/bit.cpp.i

.PHONY : src/Z80/iManager/iSet/bit/bit.i

# target to preprocess a source file
src/Z80/iManager/iSet/bit/bit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/bit/bit.cpp.i
.PHONY : src/Z80/iManager/iSet/bit/bit.cpp.i

src/Z80/iManager/iSet/bit/bit.s: src/Z80/iManager/iSet/bit/bit.cpp.s

.PHONY : src/Z80/iManager/iSet/bit/bit.s

# target to generate assembly for a file
src/Z80/iManager/iSet/bit/bit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/bit/bit.cpp.s
.PHONY : src/Z80/iManager/iSet/bit/bit.cpp.s

src/Z80/iManager/iSet/cpuctl/cpuctl.o: src/Z80/iManager/iSet/cpuctl/cpuctl.cpp.o

.PHONY : src/Z80/iManager/iSet/cpuctl/cpuctl.o

# target to build an object file
src/Z80/iManager/iSet/cpuctl/cpuctl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/cpuctl/cpuctl.cpp.o
.PHONY : src/Z80/iManager/iSet/cpuctl/cpuctl.cpp.o

src/Z80/iManager/iSet/cpuctl/cpuctl.i: src/Z80/iManager/iSet/cpuctl/cpuctl.cpp.i

.PHONY : src/Z80/iManager/iSet/cpuctl/cpuctl.i

# target to preprocess a source file
src/Z80/iManager/iSet/cpuctl/cpuctl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/cpuctl/cpuctl.cpp.i
.PHONY : src/Z80/iManager/iSet/cpuctl/cpuctl.cpp.i

src/Z80/iManager/iSet/cpuctl/cpuctl.s: src/Z80/iManager/iSet/cpuctl/cpuctl.cpp.s

.PHONY : src/Z80/iManager/iSet/cpuctl/cpuctl.s

# target to generate assembly for a file
src/Z80/iManager/iSet/cpuctl/cpuctl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/cpuctl/cpuctl.cpp.s
.PHONY : src/Z80/iManager/iSet/cpuctl/cpuctl.cpp.s

src/Z80/iManager/iSet/iSet.o: src/Z80/iManager/iSet/iSet.cpp.o

.PHONY : src/Z80/iManager/iSet/iSet.o

# target to build an object file
src/Z80/iManager/iSet/iSet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/iSet.cpp.o
.PHONY : src/Z80/iManager/iSet/iSet.cpp.o

src/Z80/iManager/iSet/iSet.i: src/Z80/iManager/iSet/iSet.cpp.i

.PHONY : src/Z80/iManager/iSet/iSet.i

# target to preprocess a source file
src/Z80/iManager/iSet/iSet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/iSet.cpp.i
.PHONY : src/Z80/iManager/iSet/iSet.cpp.i

src/Z80/iManager/iSet/iSet.s: src/Z80/iManager/iSet/iSet.cpp.s

.PHONY : src/Z80/iManager/iSet/iSet.s

# target to generate assembly for a file
src/Z80/iManager/iSet/iSet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/iSet.cpp.s
.PHONY : src/Z80/iManager/iSet/iSet.cpp.s

src/Z80/iManager/iSet/incdecaddsub/incdecaddsub.o: src/Z80/iManager/iSet/incdecaddsub/incdecaddsub.cpp.o

.PHONY : src/Z80/iManager/iSet/incdecaddsub/incdecaddsub.o

# target to build an object file
src/Z80/iManager/iSet/incdecaddsub/incdecaddsub.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/incdecaddsub/incdecaddsub.cpp.o
.PHONY : src/Z80/iManager/iSet/incdecaddsub/incdecaddsub.cpp.o

src/Z80/iManager/iSet/incdecaddsub/incdecaddsub.i: src/Z80/iManager/iSet/incdecaddsub/incdecaddsub.cpp.i

.PHONY : src/Z80/iManager/iSet/incdecaddsub/incdecaddsub.i

# target to preprocess a source file
src/Z80/iManager/iSet/incdecaddsub/incdecaddsub.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/incdecaddsub/incdecaddsub.cpp.i
.PHONY : src/Z80/iManager/iSet/incdecaddsub/incdecaddsub.cpp.i

src/Z80/iManager/iSet/incdecaddsub/incdecaddsub.s: src/Z80/iManager/iSet/incdecaddsub/incdecaddsub.cpp.s

.PHONY : src/Z80/iManager/iSet/incdecaddsub/incdecaddsub.s

# target to generate assembly for a file
src/Z80/iManager/iSet/incdecaddsub/incdecaddsub.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/incdecaddsub/incdecaddsub.cpp.s
.PHONY : src/Z80/iManager/iSet/incdecaddsub/incdecaddsub.cpp.s

src/Z80/iManager/iSet/rotate/rotate.o: src/Z80/iManager/iSet/rotate/rotate.cpp.o

.PHONY : src/Z80/iManager/iSet/rotate/rotate.o

# target to build an object file
src/Z80/iManager/iSet/rotate/rotate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/rotate/rotate.cpp.o
.PHONY : src/Z80/iManager/iSet/rotate/rotate.cpp.o

src/Z80/iManager/iSet/rotate/rotate.i: src/Z80/iManager/iSet/rotate/rotate.cpp.i

.PHONY : src/Z80/iManager/iSet/rotate/rotate.i

# target to preprocess a source file
src/Z80/iManager/iSet/rotate/rotate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/rotate/rotate.cpp.i
.PHONY : src/Z80/iManager/iSet/rotate/rotate.cpp.i

src/Z80/iManager/iSet/rotate/rotate.s: src/Z80/iManager/iSet/rotate/rotate.cpp.s

.PHONY : src/Z80/iManager/iSet/rotate/rotate.s

# target to generate assembly for a file
src/Z80/iManager/iSet/rotate/rotate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/iManager/iSet/rotate/rotate.cpp.s
.PHONY : src/Z80/iManager/iSet/rotate/rotate.cpp.s

src/Z80/memoryManager/memoryManager.o: src/Z80/memoryManager/memoryManager.cpp.o

.PHONY : src/Z80/memoryManager/memoryManager.o

# target to build an object file
src/Z80/memoryManager/memoryManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/memoryManager/memoryManager.cpp.o
.PHONY : src/Z80/memoryManager/memoryManager.cpp.o

src/Z80/memoryManager/memoryManager.i: src/Z80/memoryManager/memoryManager.cpp.i

.PHONY : src/Z80/memoryManager/memoryManager.i

# target to preprocess a source file
src/Z80/memoryManager/memoryManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/memoryManager/memoryManager.cpp.i
.PHONY : src/Z80/memoryManager/memoryManager.cpp.i

src/Z80/memoryManager/memoryManager.s: src/Z80/memoryManager/memoryManager.cpp.s

.PHONY : src/Z80/memoryManager/memoryManager.s

# target to generate assembly for a file
src/Z80/memoryManager/memoryManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/memoryManager/memoryManager.cpp.s
.PHONY : src/Z80/memoryManager/memoryManager.cpp.s

src/Z80/z80.o: src/Z80/z80.cpp.o

.PHONY : src/Z80/z80.o

# target to build an object file
src/Z80/z80.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/z80.cpp.o
.PHONY : src/Z80/z80.cpp.o

src/Z80/z80.i: src/Z80/z80.cpp.i

.PHONY : src/Z80/z80.i

# target to preprocess a source file
src/Z80/z80.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/z80.cpp.i
.PHONY : src/Z80/z80.cpp.i

src/Z80/z80.s: src/Z80/z80.cpp.s

.PHONY : src/Z80/z80.s

# target to generate assembly for a file
src/Z80/z80.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/Z80/z80.cpp.s
.PHONY : src/Z80/z80.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Z80Emu.out.dir/build.make CMakeFiles/Z80Emu.out.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Z80Emu.out"
	@echo "... src/Z80/iManager/iManager.o"
	@echo "... src/Z80/iManager/iManager.i"
	@echo "... src/Z80/iManager/iManager.s"
	@echo "... src/Z80/iManager/iSet/BIT/bitIS.o"
	@echo "... src/Z80/iManager/iSet/BIT/bitIS.i"
	@echo "... src/Z80/iManager/iSet/BIT/bitIS.s"
	@echo "... src/Z80/iManager/iSet/IXCB/ixcb.o"
	@echo "... src/Z80/iManager/iSet/IXCB/ixcb.i"
	@echo "... src/Z80/iManager/iSet/IXCB/ixcb.s"
	@echo "... src/Z80/iManager/iSet/IYCB/iycb.o"
	@echo "... src/Z80/iManager/iSet/IYCB/iycb.i"
	@echo "... src/Z80/iManager/iSet/IYCB/iycb.s"
	@echo "... src/Z80/iManager/iSet/MAINIS/mainIs.o"
	@echo "... src/Z80/iManager/iSet/MAINIS/mainIs.i"
	@echo "... src/Z80/iManager/iSet/MAINIS/mainIs.s"
	@echo "... src/Z80/iManager/iSet/arithmetic/arithmetic.o"
	@echo "... src/Z80/iManager/iSet/arithmetic/arithmetic.i"
	@echo "... src/Z80/iManager/iSet/arithmetic/arithmetic.s"
	@echo "... src/Z80/iManager/iSet/bit/bit.o"
	@echo "... src/Z80/iManager/iSet/bit/bit.i"
	@echo "... src/Z80/iManager/iSet/bit/bit.s"
	@echo "... src/Z80/iManager/iSet/cpuctl/cpuctl.o"
	@echo "... src/Z80/iManager/iSet/cpuctl/cpuctl.i"
	@echo "... src/Z80/iManager/iSet/cpuctl/cpuctl.s"
	@echo "... src/Z80/iManager/iSet/iSet.o"
	@echo "... src/Z80/iManager/iSet/iSet.i"
	@echo "... src/Z80/iManager/iSet/iSet.s"
	@echo "... src/Z80/iManager/iSet/incdecaddsub/incdecaddsub.o"
	@echo "... src/Z80/iManager/iSet/incdecaddsub/incdecaddsub.i"
	@echo "... src/Z80/iManager/iSet/incdecaddsub/incdecaddsub.s"
	@echo "... src/Z80/iManager/iSet/rotate/rotate.o"
	@echo "... src/Z80/iManager/iSet/rotate/rotate.i"
	@echo "... src/Z80/iManager/iSet/rotate/rotate.s"
	@echo "... src/Z80/memoryManager/memoryManager.o"
	@echo "... src/Z80/memoryManager/memoryManager.i"
	@echo "... src/Z80/memoryManager/memoryManager.s"
	@echo "... src/Z80/z80.o"
	@echo "... src/Z80/z80.i"
	@echo "... src/Z80/z80.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

